# Generated by Django 3.1.6 on 2024-09-12 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20240910_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterials',
            name='subject',
            field=models.CharField(choices=[('IT', 'IT'), ('Business Management', 'Business Management'), ('Hotel Management', 'Hotel Management'), ('Social Work', 'Social Work'), ('Stories and Poems', 'Stories and Poems')], max_length=50),
        ),
    ]
