# Generated by Django 3.1.6 on 2024-09-12 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20240912_1135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studymaterials',
            options={'ordering': ['-date_posted']},
        ),
        migrations.AlterField(
            model_name='studymaterials',
            name='subject',
            field=models.CharField(choices=[('IT', 'Information Technology'), ('Business Management', 'Business Management'), ('Hotel Management', 'Hotel Management'), ('Social Work', 'Social Work'), ('Stories and Poems', 'Stories and Poems')], max_length=50),
        ),
    ]
