# Generated by Django 3.1.6 on 2024-09-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20240912_1137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studymaterials',
            options={},
        ),
        migrations.AddField(
            model_name='studymaterials',
            name='external_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='studymaterials',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='study_materials_pdfs/'),
        ),
        migrations.AddField(
            model_name='studymaterials',
            name='short_description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='studymaterials',
            name='subject',
            field=models.CharField(choices=[('IT', 'IT'), ('Business Management', 'Business Management'), ('Hotel Management', 'Hotel Management'), ('Social Work', 'Social Work'), ('Stories and Poems', 'Stories and Poems')], max_length=50),
        ),
    ]
