# Generated by Django 4.2.2 on 2024-09-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20240912_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studymaterials',
            name='external_link',
        ),
        migrations.RemoveField(
            model_name='studymaterials',
            name='pdf_file',
        ),
        migrations.RemoveField(
            model_name='studymaterials',
            name='short_description',
        ),
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studymaterials',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studymaterials',
            name='subject',
            field=models.CharField(choices=[('Compiler', 'Compiler'), ('MM', 'MM'), ('Java', 'Java'), ('SPM', 'SPM'), ('BRM', 'BRM')], max_length=50),
        ),
        migrations.AlterField(
            model_name='todo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
