# Generated by Django 4.2.2 on 2024-09-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_note_id_alter_profile_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterials',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='study_materials/pdf_files/'),
        ),
    ]
